
POST http://localhost:3000/api/v1/register
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk0MDIwMDQ3LCJleHAiOjE2OTQwMjM2NDd9.HySHe9tztCnRGzt0GrG_x6X-YCurjMXj7n2D8eT8Mlw

{
    "number": "09079417401",
    "first_name": "Divine",
    "last_name": "Iso",
    "email": "test7@gmil.com",
    "name": "ubong",
    "password": "CypherC",
    "passwordConfirmation": "CypherC"
}

###

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "Email": "iso@gmail.com",
    "Password": "000000"
}
###

GET http://localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjgsImZpcnN0TmFtZSI6IkRpdmluZSIsImxhc3ROYW1lIjoiSXNvIiwiZ2VuZGVyIjoibSIsImVtYWlsIjoidGVzdEBnbWlsLmNvbSIsIm51bWJlciI6MjE0NzQ4MzY0NywiY3JlYXRlZF9hdCI6IjAwMDAtMDAtMDAgMDA6MDA6MDAiLCJnb29nX3JlZnJlc2hfdG9rZW4iOm51bGwsImFjY2Vzc190b2tlbiI6bnVsbCwicGxhbiI6bnVsbCwic3RhdHVzIjpudWxsLCJzZXNzaW9uX3VyaSI6bnVsbCwiY291bnRfdXBsb2FkcyI6bnVsbCwiYnl0ZXMgX3RvdGFsIjpudWxsLCJ1c2VyX2lkIjpudWxsfSwiaWF0IjoxNjk1Mzc5MDEzLCJleHAiOjE2OTUzODI2MTN9.yj6Jtw2KgdyjPGUnz8vhWcUE4o7hFQZO9ZuVgolIbvos

